### PR TITLE
network-modeling writeup

### PR DESCRIPTION
**Pull request by samlalwani**
Writeup on how I use Dask to model wireless networks alongs with a couple of links that show a few examples.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thank you for writing this up @samlalwani !  To me it looks like an intersting and challenging application.  

If possible, can I ask you to rearrange a few things?  

-  Much of the content in "How Dask Helps" seems like it might be more appropriate in "The problem I'm trying to solve".  Ideally we'd like to separate these two out a little bit.
-  As we move things out of the "How Dask Helps" section could I ask you fill in that space with additional context about how you use Dask instead?  For example:
    -  You mention that you run across multiple machines.  Roughly how many, and how do you manage these machines?  For example are you renting machines from AWS or do you have an in-house cluster?
    - You say "plus we could write much more complex logic", I'm curious, is there something reasonably simple we could say here to convey what kinds of complexity you're dealing with that someone from another domain might understand?  
    - "share our computing pool between multiple users" people often ask about how Dask is used in a setting with many people using the same machines.  If you add a little bit of additional context here I suspect that people would be interested in hearing about it.
    - It sounds like you start with dask.dataframe to do basic data ingestion and preprocssing, and then switch to dask.delayed for more custom logic.  Is this correct?

Thank you again for taking the time to write this up.  I appreciate it.

**Comment by mrocklin** [comment]
Also, I notice from your linked-in account that you work for Qualcomm.  Is this something you're able to mention in the "who am I?" section.  No worries if not, I understand that some companies can be sensitive about things like this.

**Comment by mrocklin** [comment]
This looks great to me.  Thank you @samlalwani.  I've pushed up some language edits that I *think* are minor.  Can you take a look at these changes and let me know if you're ok with them?

**Comment by samlalwani** [comment]
Hi Matthew,
I am fine with all your edits.
Some of the work described here was done by me in Qualcomm but I do not represent Qualcomm's position in the writeup. I had a computing problem, which I went ahead and solved using Dask. 

The biggest advantage I get from Dask is that it allows me to take advantage of wider Python ecosystem libraries on these large data sets.

**Comment by mrocklin** [comment]
A couple of final edits on your edits :)

**Comment by samlalwani** [comment]
I am fine with the edits

**Comment by mrocklin** [comment]
Great.  Merging this in.  Thank you again for writing this up @samlalwani .  It's a great example and I like that it's quite different from the other applications that are up there so far.  This should be live in a minute or two.

**Comment by samlalwani** [comment]
cool my first github post.
By the way we had few chats during first AnacondaCon where your recommended
I look at delayed. Before that I was using custom graphs for my code .
My colleague visited the second Anacondacon event.

Sameer

**Comment by mrocklin** [comment]
Glad to hear that it worked out for you.  This post is really helpful for
the project, so I'm very grateful for the conversation :)

**Comment by samlalwani** [comment]
The Dask distributed documentation never mentions that multiple people can
connect to the same scheduler and share the workers. That worked very well
for our team and allowed us to efficiently utilize the computing resources.
In a small team with limited resources that works out well.

Maybe you can add a section about that in the documentation.

**Pull request merged**
