### PR TITLE
pangeo story

### PR DESCRIPTION
**Pull request by rabernat**
I'm happy to iterate on this as needed.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks @rabernat .  I appreciate this.  I've pushed a couple edits, mostly removing personal reference to myself, adding a couple of small language edits, and adding links at the bottom for the various software projects.   Are you comfortable with these changes?

**Comment by mrocklin** [comment]
OK to merge?

**Comment by mrocklin** [comment]
Merging this for now.  Happy to revert any changes retroactively.

**Comment by rabernat** [comment]
Sorry I never followed up to your questions. I left for a transatlantic trip just after submitting this.

**Pull request merged**
